export const FETCH_TWEETS = 'FETCH_TWEETS'
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS'
export const FETCH_TWEETS_FAILURE = 'FETCH_TWEETS_FAILURE'

export const PARSE_TWEETS = 'PARSE_TWEETS'
export const PARSE_TWEETS_SUCCESS = 'PARSE_TWEETS_SUCCESS'

export const ANALYZE_SENTIMENT = 'ANALYZE_SENTIMENT'
export const ANALYZE_SENTIMENT_SUCCESS = 'ANALYZE_SENTIMENT_SUCCESS'

export const ADD_TWEET_FINAL_FORM = 'ADD_TWEET_FINAL_FORM'

export const TWEETS_LOADING = 'TWEETS_LOADING'

export const TWITTER_API_URL = 'https://api.twitter.com/1.1/search/tweets.json'

export const TWITTER_BEARER_TOKEN =
  'AAAAAAAAAAAAAAAAAAAAAGxP8AAAAAAAvJnDQ9cWPccJf467p6K3fn4F4iU%3D1vV7jBIiIwv3DzlTgTlaKlTeG285SVwJuah9oP3nZrl2Aalzu4'
